---
abstract: 'Simple Moose-Roles to implement the Observer Pattern'
author:
  - 'Thomas Müller <tmueller@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Observer
requires:
  List::MoreUtils: 0.33
  Moose: 2.0603
  MooseX::Role::Parameterized: 1.00
  Test::More: 0.98
  strict: 0
  warnings: 0
version: 0.009
